apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hpa

spec:
  replicas: 1

  selector:
    matchLabels:
      app: go-hpa
  
  template:
    metadata:
      labels:
        app: go-hpa
    spec:
      containers:
      - name: go-hpa
        image: robsantossilva/go-hpa:latest
        ports:
        - containerPort: 8000

        resources:
          requests:
            #memory: "100Mi"
            cpu: "50m"
          limits:
            #memory: "200Mi"
            cpu: "100m"

---

apiVersion: v1
kind: Service
metadata:
  name: go-hpa-service
  labels:
    app: go-hpa-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8000
  selector:
    app: go-hpa

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-hpa-hpa
spec:
  maxReplicas: 6
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: go-hpa
  targetCPUUtilizationPercentage: 15